# Generated by Django 4.0.3 on 2022-03-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Guide',
            fields=[
                ('guide', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pass_g1', models.CharField(blank=True, default='xyz', max_length=50, null=True)),
                ('pass_g2', models.CharField(blank=True, default='xyz', max_length=50, null=True)),
                ('m_g', models.CharField(max_length=10)),
                ('eid_g', models.EmailField(max_length=254)),
                ('total_grps', models.IntegerField(blank=True, max_length=3)),
                ('dept', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('inst', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Group',
            fields=[
                ('grp_number', models.IntegerField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=50)),
                ('mem1', models.CharField(max_length=50)),
                ('mem2', models.CharField(max_length=50)),
                ('eid1', models.EmailField(max_length=254)),
                ('eid2', models.EmailField(max_length=254)),
                ('mob_number1', models.CharField(max_length=10)),
                ('mob_number2', models.CharField(max_length=10)),
                ('pass_p1', models.CharField(blank=True, default='xyz', max_length=10, null=True)),
                ('pass_p2', models.CharField(blank=True, default='xyz', max_length=10, null=True)),
                ('f1', models.FileField(blank=True, null=True, upload_to='')),
                ('f2', models.FileField(blank=True, null=True, upload_to='')),
                ('f3', models.FileField(blank=True, null=True, upload_to='')),
                ('remark', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('status', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('flag', models.BooleanField(default='False')),
                ('guide', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='new.project_guide')),
            ],
        ),
    ]
